groups:
  - name: apps-alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(process_cpu_seconds_total[1m])) by (instance) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage has exceeded 90% on instance {{ $labels.instance }} for more than 5 minutes."
          
      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low memory available on {{ $labels.instance }}"
          description: "Memory available is less than 10% on instance {{ $labels.instance }} for more than 5 minutes."
