groups:
  - name: apps-recording-rules
    rules:
      - record: job:node_cpu:rate5m
        expr: rate(node_cpu_seconds_total[5m])
        
      - record: job:node_memory:usage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes
