apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxi
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: false
  - name: Loki
    type: loki
    access: proxi
    url: http://loki:3100
  - name: Tempo
    type: tempo
    access: proxi
    basicAuth: false
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: 'Prometheus'
      serviceMap:
        datasourceUid: 'Prometheus'
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    basicAuth: false
    jsonData:
      tracesToMetrics:
        datasourceUid: 'Prometheus'
