global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'email-receiver'
  email_configs:
  - to: 'team@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'alertmanager'
    auth_password: 'password'
    send_resolved: true
    html: |
      <h1>{{ .CommonAnnotations.summary }}</h1>
      <p>{{ .CommonAnnotations.description }}</p>
      <p>Labels:</p>
      <ul>
        {{ range .CommonLabels.SortedPairs }}
        <li><strong>{{ .Name }}</strong>: {{ .Value }}</li>
        {{ end }}
      </ul>

