global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rule/alert_rules.yml"
  - "rule/recording_rules.yml"

 
scrape_configs:
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']  
  - job_name: 'tempo'
    static_configs:
        - targets: ['tempo:3200']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    file_sd_configs:
      - files:
          - '/etc/prometheus/file_sd/*.json'
    relabel_configs:
      - source_labels: [__meta_app_name]
        regex: .*/([^/]+)\.json
        target_label: __tmp_file_name
        replacement: $1
        action: replace

      - source_labels: [__tmp_file_name]
        regex: (.+)
        target_label: app_name
        replacement: $1
        action: replace

      - source_labels: [__address__]
        target_label: instance
        action: replace
      
      - action: labelmap
        regex: __meta_(.+)
      
        
        
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - localhost:9093
